import { TechIcons } from './types'

/*
  Taken from simpleicons:
  icon list: https://simpleicons.org/
  corresponding slug: https://github.com/simple-icons/simple-icons/blob/develop/slugs.md
*/

const techlist: Array<TechIcons> = [
  { name: '.NET', icon: 'dotnet' },
  { name: 'AdonisJS', icon: 'adonisjs' },
  { name: 'Alpine.js', icon: 'alpinedotjs' },
  { name: 'Amazon AWS', icon: 'amazonaws' },
  { name: 'Amazon DynamoDB', icon: 'amazondynamodb' },
  { name: 'Amazon S3', icon: 'amazons3' },
  { name: 'AMP', icon: 'amp' },
  { name: 'Android', icon: 'android' },
  { name: 'Angular', icon: 'angular' },
  { name: 'AngularJS', icon: 'angularjs' },
  { name: 'Ant Design', icon: 'antdesign' },
  { name: 'Apollo GraphQL', icon: 'apollographql' },
  { name: 'Arduino', icon: 'arduino' },
  { name: 'AssemblyScript', icon: 'assemblyscript' },
  { name: 'Astro', icon: 'astro' },
  { name: 'Aurelia', icon: 'aurelia' },
  { name: 'Auth0', icon: 'auth0' },
  { name: 'Authy', icon: 'authy' },
  { name: 'Autoprefixer', icon: 'autoprefixer' },
  { name: 'AWS Amplify', icon: 'awsamplify' },
  { name: 'Azure Artifacts', icon: 'azureartifacts' },
  { name: 'Azure Data Explorer', icon: 'azuredataexplorer' },
  { name: 'Azure DevOps', icon: 'azuredevops' },
  { name: 'Azure Functions', icon: 'azurefunctions' },
  { name: 'Azure Pipelines', icon: 'azurepipelines' },
  { name: 'Babel', icon: 'babel' },
  { name: 'Backbone.js', icon: 'backbonedotjs' },
  { name: 'Bitbucket', icon: 'bitbucket' },
  { name: 'Bootstrap', icon: 'bootstrap' },
  { name: 'Buefy', icon: 'buefy' },
  { name: 'Bulma', icon: 'bulma' },
  { name: 'C', icon: 'c' },
  { name: 'C Sharp', icon: 'csharp' },
  { name: 'C++', icon: 'cplusplus' },
  { name: 'CakePHP', icon: 'cakephp' },
  { name: 'Canva', icon: 'canva' },
  { name: 'Capacitor', icon: 'capacitor' },
  { name: 'Chakra UI', icon: 'chakraui' },
  { name: 'Chart.js', icon: 'chartdotjs' },
  { name: 'CheckiO', icon: 'checkio' },
  { name: 'Circle', icon: 'circle' },
  { name: 'CircleCI', icon: 'circleci' },
  { name: 'Cirrus CI', icon: 'cirrusci' },
  { name: 'Clojure', icon: 'clojure' },
  { name: 'Cloudflare', icon: 'cloudflare' },
  { name: 'Clyp', icon: 'clyp' },
  { name: 'CMake', icon: 'cmake' },
  { name: 'CodeceptJS', icon: 'codeceptjs' },
  { name: 'CodePen', icon: 'codepen' },
  { name: 'CodeSandbox', icon: 'codesandbox' },
  { name: 'CoffeeScript', icon: 'coffeescript' },
  { name: 'Composer', icon: 'composer' },
  { name: 'Contentful', icon: 'contentful' },
  { name: 'Couchbase', icon: 'couchbase' },
  { name: 'cPanel', icon: 'cpanel' },
  { name: 'Craft CMS', icon: 'craftcms' },
  { name: 'Create React App', icon: 'createreactapp' },
  { name: 'Creative Commons', icon: 'creativecommons' },
  { name: 'CSS3', icon: 'css3' },
  { name: 'Cypress', icon: 'cypress' },
  { name: 'D3.js', icon: 'd3dotjs' },
  { name: 'Dart', icon: 'dart' },
  { name: 'DataCamp', icon: 'datacamp' },
  { name: 'Datadog', icon: 'datadog' },
  { name: 'DataGrip', icon: 'datagrip' },
  { name: 'DatoCMS', icon: 'datocms' },
  { name: 'Deno', icon: 'deno' },
  { name: 'Dependabot', icon: 'dependabot' },
  { name: 'Discord', icon: 'discord' },
  { name: 'Disqus', icon: 'disqus' },
  { name: 'Docker', icon: 'docker' },
  { name: 'Drupal', icon: 'drupal' },
  { name: 'EditorConfig', icon: 'editorconfig' },
  { name: 'Elastic', icon: 'elastic' },
  { name: 'Elastic Cloud', icon: 'elasticcloud' },
  { name: 'Elastic Stack', icon: 'elasticstack' },
  { name: 'Elasticsearch', icon: 'elasticsearch' },
  { name: 'Electron', icon: 'electron' },
  { name: 'Eleventy', icon: 'eleventy' },
  { name: 'Elixir', icon: 'elixir' },
  { name: 'Elm', icon: 'elm' },
  { name: 'Ember.js', icon: 'emberdotjs' },
  { name: 'esbuild', icon: 'esbuild' },
  { name: 'ESLint', icon: 'eslint' },
  { name: 'Expo', icon: 'expo' },
  { name: 'Express', icon: 'express' },
  { name: 'Fastify', icon: 'fastify' },
  { name: 'Fastly', icon: 'fastly' },
  { name: 'Firebase', icon: 'firebase' },
  { name: 'Flutter', icon: 'flutter' },
  { name: 'Font Awesome', icon: 'fontawesome' },
  { name: 'FontBase', icon: 'fontbase' },
  { name: 'Formstack', icon: 'formstack' },
  { name: 'Foursquare', icon: 'foursquare' },
  { name: 'Framer', icon: 'framer' },
  { name: 'Framework7', icon: 'framework7' },
  { name: 'Gatsby', icon: 'gatsby' },
  { name: 'Git', icon: 'git' },
  { name: 'GitHub', icon: 'github' },
  { name: 'GitHub Actions', icon: 'githubactions' },
  { name: 'GitHub Pages', icon: 'githubpages' },
  { name: 'GitLab', icon: 'gitlab' },
  { name: 'Go', icon: 'go' },
  { name: 'GoLand', icon: 'goland' },
  { name: 'Google Analytics', icon: 'googleanalytics' },
  { name: 'Google Cloud', icon: 'googlecloud' },
  { name: 'Google Fonts', icon: 'googlefonts' },
  { name: 'Google Maps', icon: 'googlemaps' },
  { name: 'Google Street View', icon: 'googlestreetview' },
  { name: 'Google Tag Manager', icon: 'googletagmanager' },
  { name: 'Gradle', icon: 'gradle' },
  { name: 'Grafana', icon: 'grafana' },
  { name: 'GraphQL', icon: 'graphql' },
  { name: 'Gravatar', icon: 'gravatar' },
  { name: 'GreenSock', icon: 'greensock' },
  { name: 'Gridsome', icon: 'gridsome' },
  { name: 'Grunt', icon: 'grunt' },
  { name: 'gulp', icon: 'gulp' },
  { name: 'Handlebars.js', icon: 'handlebarsdotjs' },
  { name: 'Haskell', icon: 'haskell' },
  { name: 'Hasura', icon: 'hasura' },
  { name: 'HelpDesk', icon: 'helpdesk' },
  { name: 'HERE', icon: 'here' },
  { name: 'Heroku', icon: 'heroku' },
  { name: 'Houdini', icon: 'houdini' },
  { name: 'HTML5', icon: 'html5' },
  { name: 'i18next', icon: 'i18next' },
  { name: 'IBM Cloud', icon: 'ibmcloud' },
  { name: 'Iconfinder', icon: 'iconfinder' },
  { name: 'Iconify', icon: 'iconify' },
  { name: 'IconJar', icon: 'iconjar' },
  { name: 'Icons8', icon: 'icons8' },
  { name: 'Imgur', icon: 'imgur' },
  { name: 'Immer', icon: 'immer' },
  { name: 'InfluxDB', icon: 'influxdb' },
  { name: 'InteractJS', icon: 'interactjs' },
  { name: 'Intercom', icon: 'intercom' },
  { name: 'Ionic', icon: 'ionic' },
  { name: 'iOS', icon: 'ios' },
  { name: 'Jamstack', icon: 'jamstack' },
  { name: 'Jasmine', icon: 'jasmine' },
  { name: 'Java', icon: 'java' },
  { name: 'JavaScript', icon: 'javascript' },
  { name: 'Jekyll', icon: 'jekyll' },
  { name: 'Jenkins', icon: 'jenkins' },
  { name: 'Jenkins X', icon: 'jenkinsx' },
  { name: 'Jest', icon: 'jest' },
  { name: 'Joomla', icon: 'joomla' },
  { name: 'jQuery', icon: 'jquery' },
  { name: 'jsDelivr', icon: 'jsdelivr' },
  { name: 'JSON', icon: 'json' },
  { name: 'JSON Web Tokens', icon: 'jsonwebtokens' },
  { name: 'JSS', icon: 'jss' },
  { name: 'Julia', icon: 'julia' },
  { name: 'Keras', icon: 'keras' },
  { name: 'Koa', icon: 'koa' },
  { name: 'Konva', icon: 'konva' },
  { name: 'Kotlin', icon: 'kotlin' },
  { name: 'Leaflet', icon: 'leaflet' },
  { name: 'Lerna', icon: 'lerna' },
  { name: 'Less', icon: 'less' },
  { name: "Let's Encrypt", icon: 'letsencrypt' },
  { name: 'Lighthouse', icon: 'lighthouse' },
  { name: 'Linktree', icon: 'linktree' },
  { name: 'Linux Containers', icon: 'linuxcontainers' },
  { name: 'Lodash', icon: 'lodash' },
  { name: 'Lua', icon: 'lua' },
  { name: 'MailChimp', icon: 'mailchimp' },
  { name: 'Mapbox', icon: 'mapbox' },
  { name: 'MariaDB', icon: 'mariadb' },
  { name: 'Markdown', icon: 'markdown' },
  { name: 'Mastodon', icon: 'mastodon' },
  { name: 'Material Design', icon: 'materialdesign' },
  { name: 'Material Design Icons', icon: 'materialdesignicons' },
  { name: 'Meteor', icon: 'meteor' },
  { name: 'MicroPython', icon: 'micropython' },
  { name: 'Microsoft Azure', icon: 'microsoftazure' },
  { name: 'Microsoft OneDrive', icon: 'microsoftonedrive' },
  { name: 'Microsoft SharePoint', icon: 'microsoftsharepoint' },
  { name: 'Microsoft SQL Server', icon: 'microsoftsqlserver' },
  { name: 'MobX', icon: 'mobx' },
  { name: 'MobX-State-Tree', icon: 'mobxstatetree' },
  { name: 'Mocha', icon: 'mocha' },
  { name: 'MongoDB', icon: 'mongodb' },
  { name: 'MUI', icon: 'mui' },
  { name: 'MySQL', icon: 'mysql' },
  { name: 'NativeScript', icon: 'nativescript' },
  { name: 'Neo4j', icon: 'neo4j' },
  { name: 'Neovim', icon: 'neovim' },
  { name: 'NestJS', icon: 'nestjs' },
  { name: 'Netlify', icon: 'netlify' },
  { name: 'Next.js', icon: 'nextdotjs' },
  { name: 'NGINX', icon: 'nginx' },
  { name: 'ngrok', icon: 'ngrok' },
  { name: 'Node.js', icon: 'nodedotjs' },
  { name: 'Nodemon', icon: 'nodemon' },
  { name: 'Notion', icon: 'notion' },
  { name: 'npm', icon: 'npm' },
  { name: 'Nrwl', icon: 'nrwl' },
  { name: 'NumPy', icon: 'numpy' },
  { name: 'Nuxt.js', icon: 'nuxtdotjs' },
  { name: 'Nx', icon: 'nx' },
  { name: 'OpenTelemetry', icon: 'opentelemetry' },
  { name: 'p5.js', icon: 'p5dotjs' },
  { name: 'Packagist', icon: 'packagist' },
  { name: 'pandas', icon: 'pandas' },
  { name: 'Passport', icon: 'passport' },
  { name: 'PayPal', icon: 'paypal' },
  { name: 'Perl', icon: 'perl' },
  { name: 'PHP', icon: 'php' },
  { name: 'phpMyAdmin', icon: 'phpmyadmin' },
  { name: 'Plausible Analytics', icon: 'plausibleanalytics' },
  { name: 'Plotly', icon: 'plotly' },
  { name: 'PM2', icon: 'pm2' },
  { name: 'pnpm', icon: 'pnpm' },
  { name: 'Podman', icon: 'podman' },
  { name: 'Polymer Project', icon: 'polymerproject' },
  { name: 'PostCSS', icon: 'postcss' },
  { name: 'PostgreSQL', icon: 'postgresql' },
  { name: 'Power BI', icon: 'powerbi' },
  { name: 'pre-commit', icon: 'precommit' },
  { name: 'Prettier', icon: 'prettier' },
  { name: 'Prisma', icon: 'prisma' },
  { name: 'Prismic', icon: 'prismic' },
  { name: 'Pug', icon: 'pug' },
  { name: 'Puppeteer', icon: 'puppeteer' },
  { name: 'PureScript', icon: 'purescript' },
  { name: 'PurgeCSS', icon: 'purgecss' },
  { name: 'Pusher', icon: 'pusher' },
  { name: 'PWA', icon: 'pwa' },
  { name: 'PyCharm', icon: 'pycharm' },
  { name: 'PyPI', icon: 'pypi' },
  { name: 'PyPy', icon: 'pypy' },
  { name: 'PyScaffold', icon: 'pyscaffold' },
  { name: 'Pytest', icon: 'pytest' },
  { name: 'Python', icon: 'python' },
  { name: 'PyTorch', icon: 'pytorch' },
  { name: 'PyTorch Lightning', icon: 'pytorchlightning' },
  { name: 'PyUp', icon: 'pyup' },
  { name: 'Quasar', icon: 'quasar' },
  { name: 'R', icon: 'r' },
  { name: 'React', icon: 'react' },
  { name: 'React Query', icon: 'reactquery' },
  { name: 'React Router', icon: 'reactrouter' },
  { name: 'React Table', icon: 'reacttable' },
  { name: 'ReactiveX', icon: 'reactivex' },
  { name: 'Reason', icon: 'reason' },
  { name: 'Redis', icon: 'redis' },
  { name: 'Redux', icon: 'redux' },
  { name: 'Redux-Saga', icon: 'reduxsaga' },
  { name: 'RedwoodJS', icon: 'redwoodjs' },
  { name: "Ren'Py", icon: 'renpy' },
  { name: 'reveal.js', icon: 'revealdotjs' },
  { name: 'rollup.js', icon: 'rollupdotjs' },
  { name: 'Ruby', icon: 'ruby' },
  { name: 'Ruby on Rails', icon: 'rubyonrails' },
  { name: 'Ruby Sinatra', icon: 'rubysinatra' },
  { name: 'Rust', icon: 'rust' },
  { name: 'RxDB', icon: 'rxdb' },
  { name: 'Sass', icon: 'sass' },
  { name: 'Scala', icon: 'scala' },
  { name: 'SciPy', icon: 'scipy' },
  { name: 'Scratch', icon: 'scratch' },
  { name: 'Scrutinizer CI', icon: 'scrutinizerci' },
  { name: 'Semantic UI React', icon: 'semanticuireact' },
  { name: 'Semaphore CI', icon: 'semaphoreci' },
  { name: 'Sentry', icon: 'sentry' },
  { name: 'Sequelize', icon: 'sequelize' },
  { name: 'Serverless', icon: 'serverless' },
  { name: 'Shopify', icon: 'shopify' },
  { name: 'Skypack', icon: 'skypack' },
  { name: 'Snowflake', icon: 'snowflake' },
  { name: 'Snowpack', icon: 'snowpack' },
  { name: 'Solid', icon: 'solid' },
  { name: 'Solidity', icon: 'solidity' },
  { name: 'Sourcegraph', icon: 'sourcegraph' },
  { name: 'Sourcetree', icon: 'sourcetree' },
  { name: 'Spring Boot', icon: 'springboot' },
  { name: 'SQLite', icon: 'sqlite' },
  { name: 'Square', icon: 'square' },
  { name: 'Squarespace', icon: 'squarespace' },
  { name: 'Statamic', icon: 'statamic' },
  { name: 'Storyblok', icon: 'storyblok' },
  { name: 'Storybook', icon: 'storybook' },
  { name: 'Strapi', icon: 'strapi' },
  { name: 'Stripe', icon: 'stripe' },
  { name: 'styled-components', icon: 'styledcomponents' },
  { name: 'stylelint', icon: 'stylelint' },
  { name: 'Stylus', icon: 'stylus' },
  { name: 'Supabase', icon: 'supabase' },
  { name: 'Svelte', icon: 'svelte' },
  { name: 'SVG', icon: 'svg' },
  { name: 'SVGO', icon: 'svgo' },
  { name: 'Swagger', icon: 'swagger' },
  { name: 'Swarm', icon: 'swarm' },
  { name: 'SWC', icon: 'swc' },
  { name: 'Swift', icon: 'swift' },
  { name: 'Symfony', icon: 'symfony' },
  { name: 'Symphony', icon: 'symphony' },
  { name: 'SymPy', icon: 'sympy' },
  { name: 'Tableau', icon: 'tableau' },
  { name: 'Tailwind CSS', icon: 'tailwindcss' },
  { name: 'TensorFlow', icon: 'tensorflow' },
  { name: 'Terraform', icon: 'terraform' },
  { name: 'Testing Library', icon: 'testinglibrary' },
  { name: 'Three.js', icon: 'threedotjs' },
  { name: 'Travis CI', icon: 'travisci' },
  { name: 'ts-node', icon: 'tsnode' },
  { name: 'Twilio', icon: 'twilio' },
  { name: 'Typeform', icon: 'typeform' },
  { name: 'TypeScript', icon: 'typescript' },
  { name: 'UIkit', icon: 'uikit' },
  { name: 'Unity', icon: 'unity' },
  { name: 'Unreal Engine', icon: 'unrealengine' },
  { name: 'Vagrant', icon: 'vagrant' },
  { name: 'Venmo', icon: 'venmo' },
  { name: 'Vercel', icon: 'vercel' },
  { name: 'Vite', icon: 'vite' },
  { name: 'Vue.js', icon: 'vuedotjs' },
  { name: 'Vuetify', icon: 'vuetify' },
  { name: 'Vultr', icon: 'vultr' },
  { name: 'Web3.js', icon: 'web3dotjs' },
  { name: 'WebAssembly', icon: 'webassembly' },
  { name: 'WebAuthn', icon: 'webauthn' },
  { name: 'webcomponents', icon: 'webcomponentsdotorg' },
  { name: 'Webflow', icon: 'webflow' },
  { name: 'WebGL', icon: 'webgl' },
  { name: 'Webpack', icon: 'webpack' },
  { name: 'WebRTC', icon: 'webrtc' },
  { name: 'Wiki.js', icon: 'wikidotjs' },
  { name: 'Windi CSS', icon: 'windicss' },
  { name: 'Wix', icon: 'wix' },
  { name: 'WooCommerce', icon: 'woocommerce' },
  { name: 'WordPress', icon: 'wordpress' },
  { name: 'Xamarin', icon: 'xamarin' },
  { name: 'XState', icon: 'xstate' },
  { name: 'Yarn', icon: 'yarn' }
]

export default techlist
